### ISSUE TITLE
aiopluggy

### ISSUE THREAD

**Issue by pieterb** [pytest-dev/pluggy#121]
Hi all,

Sorry, this is gonna be a long post. Let me start with what I did last week...

Looking for a good Python plugin manager, I quickly found `pluggy`. I really liked its design, but couldn't use it in its current form: I'm working on a pluggable [aiohttp](https://github.com/aio-libs/aiohttp) service, and many of my *hook functions* will be *asynchronous*; that is, they will return a coroutine that must be *awaited*.

So, I forked from `pluggy` and adapted it to work with asynchronous plugins.

To me, it seems impossible to do this in a backward compatible way: `HookCaller.__call__()` and `PluginManager.register()` need to become coroutine functions, to just name some examples. Knowing that I couldn't be backward compatible anyway, I renamed my repository to `aiopluggy` and made more breaking changes.

So, the current status is:

- The repository can be found at https://github.com/Amsterdam/aiopluggy
- Documentation can be found at https://aiopluggy.readthedocs.io/en/latest/
- Everything is still "work in progress": notably, tests are incomplete and some of the original functionality (tracing, registry manipulation) is still missing.

Once it's stable, I would like to see `aiopluggy` become part of the [aio-libs](https://github.com/aio-libs/) collection.

Of course, I don't want to proceed before telling you about what I've been doing, and ask what you think of it. Also, I don't know what the "rules" are when it comes to copyright ownership. I'd hate to "adorn with borrowed plumes" on `aiopluggy`, so I kept the authorship and list of contributors intact. Still, if anyone feels my actions so far are inappropriate, please let me know so I can make it right.

A short list of the most important changes I made to the interface:
- auto-detection of asynchronous, coroutine hook functions, which will be *awaited* at call-time.
- changed the syntax of hook marker options: instead of `@hookimplmarker(tryfirst=True)` you'll now write `@hookimplmarker.try_first`.
- auto-detection of hook wrappers. I'm not happy about this myself, though ;-(
- Removed deprecated code, including the legacy ``__multicall__`` parameter handling.
- Renamed from **pluggy** to **aiopluggy**
- Removed compatibility with Python versions before 3.5.
- Updated documentation.

I'm curious about what you think.

Kind regards,
Pieter

**Comment by nicoddemus** [comment]
Hi @pieterb,

Thanks a lot for writing. I'm not a lawyer but I think the MIT license allows you to make any derivative work that you want without breaking any copyright. Having said that is definitely nice of you to write to let us know about your `aiopluggy` fork, thanks! 👍 

While the fork is a good solution it doesn't seem to be the best solution in the long term given that we are still developing pluggy; ideally you should be able to get the new features without having to port the code manually over to your fork.

What if instead `aiopluggy` depends on `pluggy` as a package, subclassing the relevant parts and making them async, would that be a possibility? I think we are open to make some internal refactorings to facilitate/make it possible if that's the case.

**Comment by RonnyPfannschmidt** [comment]
i suspect that abstracting hook drivers will be quite mindbogglingly, i wonder if there is a way to integrate things without making it incomprehensible at the same time - if the main questions surround invocation and result collection it may be possible to reliably integrate things without too much overhead by abstracting hook callers as well as the call loop

**Comment by tgoodlet** [comment]
@pieterb I've been meaning to toy with this idea for a while but I'm glad to see you've successfully attempted it 👍.

I would actually be very partial to developing the two projects in tandem and lean towards doing as @nicoddemus suggested:
> What if instead aiopluggy depends on pluggy as a package, subclassing the relevant parts and making them async, would that be a possibility? I think we are open to make some internal refactorings to facilitate/make it possible if that's the case.

If it were up to just me I'd say introduce your new stuff to the project now under an `async` package/folder that we can only import for python 3.5+.

Having `aiopluggy` more coupled with `pluggy` would probably make both projects better in the long run as we can consolidate ideas from the `async` design and vice-versa. It would also encourage more improvements to `pluggy` core as demanded by *modern python people* (cough).
`aiopluggy` is also likely to get more adoption if it stays api compatible with `pluggy` especially if discovered by the `pytest` community for async related plugins.

They way I would have done it:
- build `aiopluggy` off of `pluggy` instead of re-writing its components
- keep the same naming unless you want to suggest adding/modifying the api in `pluggy` itself

I would actually appreciate the help in pushing forward with new features (like an async api) that we can roll out in a backwards compatible way.

**Comment by tgoodlet** [comment]
>i suspect that abstracting hook drivers will be quite mindbogglingly, i wonder if there is a way to integrate things without making it incomprehensible at the same time

Hehe I was just thinking we could use `pluggy` to make `pluggy`, *pluggable* 😆

**Comment by tgoodlet** [comment]
I've recently started using `trio` for a major project and honestly have high hopes it will eventually replace the `asyncio` ecosystem (or at least provide a more popular 3rd party alternative). I'm going to close this for now since no one seems willing to work on this at the moment and @pieterb hasn't followed up.

We can always reopen when someone comes along with that energy ;)

**Comment by nicoddemus** [comment]
> honestly have high hopes it will eventually replace the asyncio ecosystem

You and me both. 😁
