### ISSUE TITLE
clarify that all hook wrappers will still be called for firstresult=True hookspecs

### ISSUE THREAD

**Issue by notestaff** [pytest-dev/pluggy#125]
At https://pluggy.readthedocs.io/en/latest/#firstresult the docs don't say what happens with  hookimpls that are hookwrappers; I assume they will all still be called?

**Comment by tgoodlet** [comment]
@notestaff yes you are correct. 
The wrapper is called and the result of the first impl is passed to it on teardown.

The logic can be seen in the [main multi-call routine](https://github.com/pytest-dev/pluggy/blob/master/pluggy/callers.py#L172).

I will amend the docs to mention this.
Thanks for reporting :)

**Comment by tgoodlet** [comment]
Ahh also in case it's not clear (it isn't), this code works because `wrappers` are [always first in the `hookimpl` list](https://github.com/pytest-dev/pluggy/blob/master/pluggy/hooks.py#L256) passed to `_multicall`. This is something that should be made explicit.

@nicoddemus what do you think about me creating another issue for that?

**Comment by nicoddemus** [comment]
@tgoodlet sure thing, that's a good idea. Thanks for answering so quickly btw! 👍
