### ISSUE TITLE
Consider using 'entrypoints' instead of 'pkg_resources' in the future

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pluggy#183]
Came across [entrypoints](https://entrypoints.readthedocs.io/en/latest/api.html) on https://github.com/anthony-tuininga/cx_Freeze/issues/216#issuecomment-435270807, where @jaraco mentions that he considers `pkg_resources` soft-deprecated and recommends `entrypoints` as replacement.

I've made two very simple benchmarks on a `pytest` environment which has some plugins installed:

```python
# use_pkg_resources.py
import pkg_resources
print([x.name for x in pkg_resources.iter_entry_points('pytest11')])
```

```python
# use_entrypoints.py
import entrypoints
print([x.name for x in entrypoints.get_group_all('pytest11')])
```

```console
λ python use_pkg_resources.py
['xdist', 'xdist.looponfail', 'parallel', 'pytest_forked', 'hypothesispytest']
```

```console
λ python use_entrypoints.py
['hypothesispytest', 'pytest_forked', 'parallel', 'xdist', 'xdist.looponfail']
```

Timings on my Windows 10 machine with Python 3.6 (only showing time in milliseconds):

```
λ powershell -command "Measure-Command { python use_entrypoints.py }"
...
TotalMilliseconds : 161,0582
```

```
λ powershell -command "Measure-Command { python use_pkg_resources.py }"
...
TotalMilliseconds : 307,5465
```

I spent 5 minutes updating pluggy and pytest to use `entrypoints`, and it seems to work fine.

I'm writing this just as a future reference, as we probably should wait to see how `entrypoints` (which is still in version `0.2.3`) and the other modules in the linked issue will actually end up replacing `pkg_resources` in general.

**Comment by RonnyPfannschmidt** [comment]
this can nicely be combined with importlib_metadata to remove our needs for pytest as well

**Comment by RonnyPfannschmidt** [comment]
ping @asottile wrt the experiences from pre-comit

**Comment by nicoddemus** [comment]
pinging @takluyver to see if he wants to chime in as well.

**Comment by jaraco** [comment]
A quick reading of the entrypoints code tells me it supports eggs, but doesn't support importable wheels. `importlib_metadata`, on the other hand, supports importable wheels [but not eggs](https://gitlab.com/python-devs/importlib_metadata/merge_requests/25/diffs). I don't think importable wheels are used in the wild, though it would be nice for entrypoints to support that (I'll file a ticket).

**Comment by asottile** [comment]
Note that I didn't end up using `entrypoints` for pre-commit, `importlib-resources` and `importlib-metadata` were sufficient for the usecases there (all pre-commit plugins are configured in a configuration file).

I decided to profile this.

### setup

```
$ python --version --version
Python 3.7.1 (default, Oct 21 2018, 04:01:51) 
[GCC 7.3.0]
```

1. a virtualenv with lots of things installed. I've attached the full list as [`requirements.txt`](https://github.com/pytest-dev/pluggy/files/2543161/requirements.txt) (151 items)
2. [`importtime-waterfall`](https://github.com/asottile/importtime-waterfall) installed
3. A few files so this can be bootstrapped as import time:

(note: I'm intentionally abusing import side-effects for profiling, this also gives me a good idea of which parts are consuming what time)

```python
# ==> entrypoints_import.py <==
import entrypoints
```

```python
# ==> entrypoints_main.py <==
import entrypoints_import
import entrypoints_use
```

```python
# ==> entrypoints_use.py <==
import entrypoints

for ep in entrypoints.get_group_all('pytest11'):
    print(ep.name)
```

```python
# ==> pkg_resources_import.py <==
import pkg_resources
```

```python
# ==> pkg_resources_main.py <==
import pkg_resources_import
import pkg_resources_use
```

```python
# ==> pkg_resources_use.py <==
import pkg_resources

for ep in pkg_resources.iter_entry_points('pytest11'):
    print(ep.name)
```

### raw time output

(I ran each of these 5 times, below is the median time)

```console
$ time python3.7 -c ''

real	0m0.070s
user	0m0.058s
sys	0m0.012s
```

```console
$ time python3.7 -c 'import pkg_resources_main'
xdist
xdist.looponfail
timeout
pytest_mock
instafail
pytest_forked
env
pytest_cov
pytest_bench
pytest-bdd

real	0m0.182s
user	0m0.165s
sys	0m0.016s
```

```console
$ time python3.7 -c 'import entrypoints_main'
pytest_bench
pytest-bdd
pytest_cov
instafail
xdist
xdist.looponfail
timeout
pytest_mock
env
pytest_forked

real	0m0.088s
user	0m0.084s
sys	0m0.004s
```

### waterfalls

(Note that times here are `*1000` because `HAR` does not support microsecond resolution)

[pkg_resources.har.txt](https://github.com/pytest-dev/pluggy/files/2543183/pkg_resources.har.txt)
[entrypoints.har.txt](https://github.com/pytest-dev/pluggy/files/2543184/entrypoints.har.txt)

Generated with:

```console
$ importtime-waterfall pkg_resources_main --har > pkg_resources.har.txt
$ importtime-waterfall entrypoints_main --har > entrypoints.har.txt
```

I then used a har viewer:

#### `pkg_resources`

![screenshot from 2018-11-02 08-54-49](https://user-images.githubusercontent.com/1810591/47926132-0c185680-de7d-11e8-904c-dfd6cb13d2c2.png)

#### `entrypoints`

![screenshot from 2018-11-02 08-56-19](https://user-images.githubusercontent.com/1810591/47926179-2e11d900-de7d-11e8-9ec5-df104747cc6b.png)

## conclusions?

Definitely seems faster, I did a quick skim of the code (as above) and noticed it's not supporting all the import types that `pkg_resources` does (notably missing zipimport?).

You're taking the hit on the first call instead of import time which can improve your time-to-first-paint (or whatever the equivalent is for commandline apps).

I'm actually kind of surprised that it's so different in performance, they're doing essentially the same work.  `pkg_resources` imports a ton of stuff, the bulkiest being `pyparsing`, but that shouldn't change this by a factor of 2.  There must be something I'm missing.

**Comment by asottile** [comment]
One thing to note that's pretty different, `entrypoints` doesn't cache the results and so it does a full traversal every run.

Compare the following:

```python
import os
import entrypoints

for _ in range(int(os.getenv('N', '1'))):
    for ep in entrypoints.get_group_all('pytest11'):
        pass
```

```python
import os
import pkg_resources

for _ in range(int(os.getenv('N', '1'))):
    for ep in pkg_resources.iter_entry_points('pytest11'):
        pass
```

```console
$ time N=100 python entrypoints_use.py 

real	0m1.479s
user	0m1.333s
sys	0m0.146s
$ time N=100 python pkg_resources_use.py 

real	0m0.189s
user	0m0.169s
sys	0m0.020s
```

Perhaps that's where all the speed savings are made?

**Comment by asottile** [comment]
:tada:  done via `importlib-metadata`
