### ISSUE TITLE
default multicall swallows exceptions thrown by hook implementations that do not inherit from BaseException

### ISSUE THREAD

**Issue by tymonpitts** [pytest-dev/pluggy#259]
While using pytest-4.6.5 and pluggy-0.13.1 in python-2.7.6 I noticed a strange issue where some exceptions being thrown by a third-party library weren't being caught by pytest and the test reported passed. I tracked the issue down to the third-party library using exception classes that don't inherit from BaseException and the try/except/finally/return pattern used by `pluggy.callers._multicall` swallowing such exceptions.

Here's a simple repro case which is expected to raise an exception but does not. If you replace the Error class with one that inherits from BaseException then it works as expected:

```python
import pluggy

hookimpl = pluggy.HookimplMarker('test')
hookspec = pluggy.HookspecMarker('test')


class Error: pass


class HookSpecs(object):
    @hookspec
    def dummy_hook(self):
        pass


class Plugin(object):
    @hookimpl
    def dummy_hook(self):
        raise Error


manager = pluggy.PluginManager('test')
manager.add_hookspecs(HookSpecs)
manager.register(Plugin())
manager.hook.dummy_hook()  # expected to raise Error
```

I tracked this all the way to the `pluggy.callers._multicall` function which uses the following try/except/finally/return pattern (pseudo code) that causes the issue:
```python
    def _multicall(...):
        results = []
        exc_info = None
        try:
            try:
                for hook_impl in reversed(hook_impls):
                    results.append(hook_impl.function(...))
            except BaseException:  # <------- problematic line
                exc_info = sys.exc_info()
        finally:
            if exc_info:
                reraise(*exc_info)
            return results[0] if results else None
```
If you change that except statement to be a bare except then everything works as expected.

Here's a simple example that demonstrates the issue. This will always print "None" and will never raise Error:
```python
class Error: pass

def test():
    result = None
    try:
        try:
            raise Error
        except BaseException:
            result = 'handled base exception'
    finally:
        return result

print(test())
```

Are there reasons for catching only BaseException subclasses and ignoring others? I couldn't think of one but that doesn't mean there isn't one :)

**Comment by goodboy** [comment]
Hey @tymonpitts :wave: thanks for the issue!

>Are there reasons for catching only BaseException subclasses and ignoring others?

Yes. In short any errors not inheriting from `Exception` are simply incorrect.
This is a python 3 vs. 2 thing that probably we don't hear about too much just because most peeps are off Python2 (which is [now EOL :wink: ](https://pythonclock.org/)) but let's see if we can take a look.

Afaik 3rd party code [*shouldn't* inherit from `BaseException`](https://cpython-test-docs.readthedocs.io/en/latest/library/exceptions.html#BaseException) so that seems mostly correct. It's more likely that these errors are not inheriting from [`Exception`](https://cpython-test-docs.readthedocs.io/en/latest/library/exceptions.html#Exception) which **would** be incorrect. The Python exception hierarchy is [here](https://docs.python.org/3/library/exceptions.html#exception-hierarchy) for reference.

Even in the Python2 days [using a bare `except:` is considered incorrect](https://docs.python.org/2/howto/doanddont.html#except) so I'm not sure it would be good in any scenario to apply it here. You will notice the one comment at the end of that section:
>Unfortunately in Python 2.x it is possible for third-party code to raise exceptions that do not inherit from Exception, so in Python 2.x there are some cases where you may have to use a bare except: and manually re-raise the exceptions you don’t want to catch.

So it looks like using `except:` is a hack that was very unfortunately needed in the Python2 days.
Since Python2 is now now longer supported **and** this kind of 3rd party library construction is considered very wrong, I don't think it makes sense for us to try and address this problem. In fact we're more likely to drop Python2 support entirely before we would backtrack to solve this.

On top of all this the `BaseException` catch I'm pretty sure was [always in the call loop](https://github.com/pytest-dev/pluggy/blob/master/src/pluggy/callers.py#L53) so I'm not sure why this wasn't a problem before for you on older versions of `pluggy`.

I hope this gives a good explanation of why this likely won't be addressed. As a work around for your situation you are welcome to try the following:
- copy and change `_mulitcall()` to have the bare `except:`
- override the [`_HookRelay.multicall()`](https://github.com/pytest-dev/pluggy/blob/master/src/pluggy/manager.py#L84) method with this new function.

**Comment by tymonpitts** [comment]
Thanks @goodboy. I totally understand the decision to close since python2 is EOL and this is not an issue with python3. Unfortunately I'm stuck with python2 for the moment because the third-party library I mentioned is also the application my code is running within and owns the python interpreter (Houdini's hython interpreter). They are moving to python3 soon-ish so perhaps it won't be an issue for too much longer.

I worked around the issue already by implementing pytest's `pytest_pyfunc_call` hook, catching the bad errors, and re-raising them as proper Exception sub-classes.
