### ISSUE TITLE
stop using the stylechecking pytest plugins

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pluggy#36]
linting is not testing, and we should stop pretending and also add linting/metrics to the GitHub integrations

**Comment by nicoddemus** [comment]
>  linting is not testing, and we should stop pretending and also add linting/metrics to the GitHub integrations

What do you mean?

**Comment by RonnyPfannschmidt** [comment]
atm flake8 issues show up as test failures on travis, thats simply wrong on many levels

**Comment by nicoddemus** [comment]
> atm flake8 issues show up as test failures on travis, thats simply wrong on many levels

Why do you say that's wrong, would you care to elaborate? 😁

**Comment by RonnyPfannschmidt** [comment]
i consider style issues and code smells distinct from actually broken real tests

**Comment by hpk42** [comment]
sure a style failure is different from a functional test failure but then again we simply have a set of automated tests that we want to keep passing ideally for each commit.  I am fine with a PR which puts linting to tox instead of to pytest runs proper, however.  Feel free to do a PR on pluggy if you'd like to see it there, it's not a real bug or feature but just a little refactoring in my book that we may or may not do.
